# Generated by Django 4.2.17 on 2024-12-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('onetime', 'One-Time')], default='monthly', max_length=10)),
            ],
            options={
                'db_table': 'feecategorytable',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rolestable',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('roll_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=255)),
            ],
            options={
                'db_table': 'studentstable',
            },
        ),
        migrations.CreateModel(
            name='StudentFeesStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], default='Due', max_length=10)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.feecategories')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.students')),
            ],
            options={
                'db_table': 'feestatus',
            },
        ),
    ]
