# Generated by Django 4.2.17 on 2024-12-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roles',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
